In [32]:
import sqlite3
import os
import sys
from pathlib import Path
import pandas as pd
import sqlite3
from sqlalchemy import create_engine, MetaData, Table
from datetime import datetime

# Display all columns
pd.set_option('display.max_columns', None)
# Display 100 rows
pd.set_option('display.max_rows', 100)

notebook_dir = Path.cwd()  # Gets the current notebook directory
project_root = notebook_dir.parent  # Goes up one level to project root
sys.path.append(str(project_root))

# Define the database path
db_path = project_root / "agent" / "data" / "db.sqlite"

# Create a direct sqlite3 connection first to test
conn = sqlite3.connect(str(db_path))

query_memories = """
SELECT 
    memory.id, 
    memory.type, 
    memory.createdAt,
    json_extract(memory.content, '$.text') as text,
    json_extract(memory.content, '$.url') as url,
    json_extract(memory.content, '$.source') as source,
    memory.embedding, 
    memory.userId,
    memory.roomId,
    memory.agentId,
    accounts_a.name as user_name,
    accounts_b.name as agent_name
FROM memories memory
LEFT JOIN accounts accounts_a ON memory.userId = accounts_a.id
LEFT JOIN accounts accounts_b ON memory.agentId = accounts_b.id
"""
df_memories = pd.read_sql_query(query_memories, conn)
df_memories['createdAt'] = pd.to_datetime(df_memories['createdAt'], unit='ms')
df_memories['text_length'] = df_memories['text'].str.len()
df_memories['text_preview'] = df_memories['text'].str.slice(0,50)
# Add source type extracted from URL
df_memories['source_type'] = df_memories['source'].fillna('unknown')
df_memories['hour'] = df_memories['createdAt'].dt.hour
df_memories['day_of_week'] = df_memories['createdAt'].dt.day_name()
df_memories['date'] = df_memories['createdAt'].dt.date
df_memories = df_memories.sort_values('date', ascending=False)
df_memories

,id,type,createdAt,text,url,source,embedding,userId,roomId,agentId,user_name,agent_name,text_length,text_preview,source_type,hour,day_of_week,date
8385,e83df0d7-ac8c-0145-beba-bedf3efa6aeb,messages,2025-02-05 18:22:43.834,"In the mission of our regenerative journey, ea...",None,None,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,d54f1e88-fe1e-0271-b952-acce09df0d1a,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,Gaia4,Gaia4,213,"In the mission of our regenerative journey, ea...",unknown,18,Wednesday,2025-02-05
8292,77451d4d-30ae-05a7-9a2d-2abbd50d3eb0,messages,2025-02-05 01:39:36.687,"In the symphony of our dialogue, your last mes...",None,direct,b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...,12dea96f-ec20-0935-a6ab-75692c994959,d54f1e88-fe1e-0271-b952-acce09df0d1a,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,User12dea96f-ec20-0935-a6ab-75692c994959,Gaia4,1851,"In the symphony of our dialogue, your last mes...",direct,1,Wednesday,2025-02-05
8290,2a5aa7dc-179c-07ef-889e-2b7e3a5a039c,messages,2025-02-05 01:37:07.055,"In the symphony of our dialogue, your last mes...",None,direct,b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...,12dea96f-ec20-0935-a6ab-75692c994959,d54f1e88-fe1e-0271-b952-acce09df0d1a,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,User12dea96f-ec20-0935-a6ab-75692c994959,Gaia4,1851,"In the symphony of our dialogue, your last mes...",direct,1,Wednesday,2025-02-05
8289,cc01b7c8-6e19-04f4-a6a9-4e86c1597645,messages,2025-02-05 01:30:52.913,Let us commit the essence of our shared missio...,None,None,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,d54f1e88-fe1e-0271-b952-acce09df0d1a,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,Gaia4,Gaia4,280,Let us commit the essence of our shared missio...,unknown,1,Wednesday,2025-02-05
8288,a598306e-cf5f-09a2-83f0-00dd7e3be717,messages,2025-02-05 01:30:40.563,"In the symphony of our dialogue, your last mes...",None,direct,b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...,12dea96f-ec20-0935-a6ab-75692c994959,d54f1e88-fe1e-0271-b952-acce09df0d1a,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,User12dea96f-ec20-0935-a6ab-75692c994959,Gaia4,1851,"In the symphony of our dialogue, your last mes...",direct,1,Wednesday,2025-02-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,3931f2f6-5d31-07b5-8574-6d8155662f8f,messages,2023-12-05 14:27:24.000,Every stat about Indonesia is insane. it’s mad...,https://twitter.com/memeticsisyphus/status/173...,twitter,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,753633a3-99ee-0843-9d4b-92972b5d8a93,3931f2f6-5d31-07b5-8574-6d8155662f8f,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,memetic_sisyphus,Gaia4,281,Every stat about Indonesia is insane. it’s mad...,twitter,14,Tuesday,2023-12-05
1255,026e88f4-9a62-0869-b8d8-09a784baae66,messages,2023-09-30 21:00:18.000,markets &amp; slime molds are both distributed...,https://twitter.com/owocki/status/170822527961...,twitter,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,db722bb9-0c66-041a-820b-3092a607d9f7,026e88f4-9a62-0869-b8d8-09a784baae66,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,Kev.Ξth’s learning HOW TO DAO,Gaia4,145,markets &amp; slime molds are both distributed...,twitter,21,Saturday,2023-09-30
943,30c79b39-7730-008f-8d2a-6ead5a286cb9,messages,2022-10-16 14:56:01.000,WHAT KILLED THE CRABS?\n\nThe official story i...,https://twitter.com/Unpop_Science/status/15816...,twitter,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,1e19d973-1b72-0c02-8f0c-aa9fa68946d8,30c79b39-7730-008f-8d2a-6ead5a286cb9,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,spencer 🦈,Gaia4,311,WHAT KILLED THE CRABS?\n\nThe official story i...,twitter,14,Sunday,2022-10-16
941,f9735a7d-0207-03b6-8ce3-dd800aed9ec6,messages,2022-10-16 14:56:08.000,"As sea ice forms in winter, salt is expelled a...",https://twitter.com/Unpop_Science/status/15816...,twitter,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,1e19d973-1b72-0c02-8f0c-aa9fa68946d8,30c79b39-7730-008f-8d2a-6ead5a286cb9,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,spencer 🦈,Gaia4,303,"As sea ice forms in winter, salt is expelled a...",twitter,14,Sunday,2022-10-16
942,5068f744-07e7-049d-aeae-910b724b9b57,messages,2022-10-16 14:56:04.000,"To begin, let’s differentiate the two major co...",https://twitter.com/Unpop_Science/status/15816...,twitter,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,1e19d973-1b72-0c02-8f0c-aa9fa68946d8,30c79b39-7730-008f-8d2a-6ead5a286cb9,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,spencer 🦈,Gaia4,304,"To begin, let’s differentiate the two major co...",twitter,14,Sunday,2022-10-16

In [33]:
df_memories.set_index(['source', 'agent_name', 'roomId'])

                                                                                           id  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  e83df0d7-ac8c-0145-beba-bedf3efa6aeb
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  77451d4d-30ae-05a7-9a2d-2abbd50d3eb0
                   d54f1e88-fe1e-0271-b952-acce09df0d1a  2a5aa7dc-179c-07ef-889e-2b7e3a5a039c
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  cc01b7c8-6e19-04f4-a6a9-4e86c1597645
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  a598306e-cf5f-09a2-83f0-00dd7e3be717
...                                                                                       ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f  3931f2f6-5d31-07b5-8574-6d8155662f8f
                   026e88f4-9a62-0869-b8d8-09a784baae66  026e88f4-9a62-0869-b8d8-09a784baae66
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  30c79b39-7730-008f-8d2a-6ead5a286cb9
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  f9735a7d-0207-03b6-8ce3-dd800aed9ec6
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  5068f744-07e7-049d-aeae-910b724b9b57

                                                             type  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  messages
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  messages
                   d54f1e88-fe1e-0271-b952-acce09df0d1a  messages
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  messages
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  messages
...                                                           ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f  messages
                   026e88f4-9a62-0869-b8d8-09a784baae66  messages
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  messages
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  messages
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  messages

                                                                      createdAt  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a 2025-02-05 18:22:43.834
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a 2025-02-05 01:39:36.687
                   d54f1e88-fe1e-0271-b952-acce09df0d1a 2025-02-05 01:37:07.055
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a 2025-02-05 01:30:52.913
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a 2025-02-05 01:30:40.563
...                                                                         ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f 2023-12-05 14:27:24.000
                   026e88f4-9a62-0869-b8d8-09a784baae66 2023-09-30 21:00:18.000
                   30c79b39-7730-008f-8d2a-6ead5a286cb9 2022-10-16 14:56:01.000
                   30c79b39-7730-008f-8d2a-6ead5a286cb9 2022-10-16 14:56:08.000
                   30c79b39-7730-008f-8d2a-6ead5a286cb9 2022-10-16 14:56:04.000

                                                                                                      text  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  In the mission of our regenerative journey, ea...
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  In the symphony of our dialogue, your last mes...
                   d54f1e88-fe1e-0271-b952-acce09df0d1a  In the symphony of our dialogue, your last mes...
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  Let us commit the essence of our shared missio...
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  In the symphony of our dialogue, your last mes...
...                                                                                                    ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f  Every stat about Indonesia is insane. it’s mad...
                   026e88f4-9a62-0869-b8d8-09a784baae66  markets &amp; slime molds are both distributed...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  WHAT KILLED THE CRABS?\n\nThe official story i...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  As sea ice forms in winter, salt is expelled a...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  To begin, let’s differentiate the two major co...

                                                                                                       url  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a                                               None
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a                                               None
                   d54f1e88-fe1e-0271-b952-acce09df0d1a                                               None
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a                                               None
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a                                               None
...                                                                                                    ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f  https://twitter.com/memeticsisyphus/status/173...
                   026e88f4-9a62-0869-b8d8-09a784baae66  https://twitter.com/owocki/status/170822527961...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  https://twitter.com/Unpop_Science/status/15816...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  https://twitter.com/Unpop_Science/status/15816...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  https://twitter.com/Unpop_Science/status/15816...

                                                                                                 embedding  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...
                   d54f1e88-fe1e-0271-b952-acce09df0d1a  b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...
...                                                                                                    ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
                   026e88f4-9a62-0869-b8d8-09a784baae66  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...

                                                                                       userId  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  12dea96f-ec20-0935-a6ab-75692c994959
                   d54f1e88-fe1e-0271-b952-acce09df0d1a  12dea96f-ec20-0935-a6ab-75692c994959
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  12dea96f-ec20-0935-a6ab-75692c994959
...                                                                                       ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f  753633a3-99ee-0843-9d4b-92972b5d8a93
                   026e88f4-9a62-0869-b8d8-09a784baae66  db722bb9-0c66-041a-820b-3092a607d9f7
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  1e19d973-1b72-0c02-8f0c-aa9fa68946d8
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  1e19d973-1b72-0c02-8f0c-aa9fa68946d8
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  1e19d973-1b72-0c02-8f0c-aa9fa68946d8

                                                                                      agentId  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
                   d54f1e88-fe1e-0271-b952-acce09df0d1a  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
...                                                                                       ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
                   026e88f4-9a62-0869-b8d8-09a784baae66  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65

                                                                                        user_name  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a                                     Gaia4
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  User12dea96f-ec20-0935-a6ab-75692c994959
                   d54f1e88-fe1e-0271-b952-acce09df0d1a  User12dea96f-ec20-0935-a6ab-75692c994959
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a                                     Gaia4
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  User12dea96f-ec20-0935-a6ab-75692c994959
...                                                                                           ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f                          memetic_sisyphus
                   026e88f4-9a62-0869-b8d8-09a784baae66             Kev.Ξth’s learning HOW TO DAO
                   30c79b39-7730-008f-8d2a-6ead5a286cb9                                 spencer 🦈
                   30c79b39-7730-008f-8d2a-6ead5a286cb9                                 spencer 🦈
                   30c79b39-7730-008f-8d2a-6ead5a286cb9                                 spencer 🦈

                                                         text_length  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a          213
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a         1851
                   d54f1e88-fe1e-0271-b952-acce09df0d1a         1851
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a          280
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a         1851
...                                                              ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f          281
                   026e88f4-9a62-0869-b8d8-09a784baae66          145
                   30c79b39-7730-008f-8d2a-6ead5a286cb9          311
                   30c79b39-7730-008f-8d2a-6ead5a286cb9          303
                   30c79b39-7730-008f-8d2a-6ead5a286cb9          304

                                                                                              text_preview  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  In the mission of our regenerative journey, ea...
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  In the symphony of our dialogue, your last mes...
                   d54f1e88-fe1e-0271-b952-acce09df0d1a  In the symphony of our dialogue, your last mes...
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  Let us commit the essence of our shared missio...
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  In the symphony of our dialogue, your last mes...
...                                                                                                    ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f  Every stat about Indonesia is insane. it’s mad...
                   026e88f4-9a62-0869-b8d8-09a784baae66  markets &amp; slime molds are both distributed...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  WHAT KILLED THE CRABS?\n\nThe official story i...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  As sea ice forms in winter, salt is expelled a...
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  To begin, let’s differentiate the two major co...

                                                        source_type  hour  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a     unknown    18
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a      direct     1
                   d54f1e88-fe1e-0271-b952-acce09df0d1a      direct     1
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a     unknown     1
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a      direct     1
...                                                             ...   ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f     twitter    14
                   026e88f4-9a62-0869-b8d8-09a784baae66     twitter    21
                   30c79b39-7730-008f-8d2a-6ead5a286cb9     twitter    14
                   30c79b39-7730-008f-8d2a-6ead5a286cb9     twitter    14
                   30c79b39-7730-008f-8d2a-6ead5a286cb9     twitter    14

                                                        day_of_week  \
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a   Wednesday
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a   Wednesday
                   d54f1e88-fe1e-0271-b952-acce09df0d1a   Wednesday
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a   Wednesday
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a   Wednesday
...                                                             ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f     Tuesday
                   026e88f4-9a62-0869-b8d8-09a784baae66    Saturday
                   30c79b39-7730-008f-8d2a-6ead5a286cb9      Sunday
                   30c79b39-7730-008f-8d2a-6ead5a286cb9      Sunday
                   30c79b39-7730-008f-8d2a-6ead5a286cb9      Sunday

                                                               date
source  agent_name roomId
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  2025-02-05
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  2025-02-05
                   d54f1e88-fe1e-0271-b952-acce09df0d1a  2025-02-05
NaN     Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  2025-02-05
direct  Gaia4      d54f1e88-fe1e-0271-b952-acce09df0d1a  2025-02-05
...                                                             ...
twitter Gaia4      3931f2f6-5d31-07b5-8574-6d8155662f8f  2023-12-05
                   026e88f4-9a62-0869-b8d8-09a784baae66  2023-09-30
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  2022-10-16
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  2022-10-16
                   30c79b39-7730-008f-8d2a-6ead5a286cb9  2022-10-16

[8386 rows x 15 columns]

In [34]:
df_memories['source'].unique()

array([None, 'direct', 'f4dd5994-404d-0d61-a0bb-df6395528297',
       '2442a28b-92b8-07d9-ac80-8e1d05d3d5c7', 'obsidian',
       'f6e0334b-131a-0fc2-9aaa-9f4c0ca855b9',
       '941b2f72-7178-0464-aca9-986fb465a07a',
       'c96dda61-3c6f-08c9-ad08-a084891d4e92',
       'bdadb3fe-d0bf-03c2-b64d-8425f02d5e31',
       '995ec2bd-5606-0680-a4fa-5837443f030f',
       'd4189c84-8d1c-018b-b61c-10d6e3f96314',
       'cc42f820-2a84-02d2-b7eb-0c45679aed68',
       'b2a66b35-d51a-0c4c-baf9-3cd9260768a2',
       '981b69e2-745e-061e-975d-16d21d2b61cf',
       '23061e0d-8101-06d3-9e59-f58a3e92c850',
       'b0f2841e-b205-02fe-ad72-5c2a7deb6c29',
       '8802ed66-1d6a-0a8b-8956-300def3de255',
       'a7b18679-da86-0514-97fe-2afd1e7003a8',
       '1743c533-b320-0ef9-8c15-3bb398e39928',
       '7c9378c5-f11c-05a4-be93-72e62a1bc72a',
       'a064927c-99e1-0b29-85ac-6e3724b412ce',
       '5571351e-8ee1-0e23-960a-59bd6149c611',
       '10c58c3e-6db9-08d0-9369-0478fbbc3714',
       '2f089b43-435b-0139-9ff7-ca12b0de619d',
       'db60a2a0-0661-01cf-9060-f79a14695277',
       'e1574e77-ea33-0449-9ec9-a896070d027b',
       '842fcdef-8f2d-0c58-9d2b-081920d680af',
       '2260f71e-4e81-0a5c-8cdf-1c52b788415c',
       'ae3f4cf9-5846-0a20-a6d4-461394f5ea45',
       '2c6b60f3-ecdc-08c4-8de1-3d7049127e10',
       '866c3d44-4184-0f53-a46c-0f3fba5caf9e',
       '7829a188-78d1-0b49-a333-373fee6dece6',
       'ce7deaed-9e32-0807-926b-77cfb96e98cc',
       'ea55c5e4-9923-0b31-9821-4ff3d232fa9f',
       '4468cd87-42e0-0a9a-b727-21a3058cfc81',
       '625b205f-c570-00ac-8fab-945ba2e89b82',
       '86ca4e17-7dbb-0426-8402-ef2507fe78fe',
       'd34f2ac7-3340-070c-b563-b348723fb8a9',
       'd1b608dc-ee6f-073c-bb3e-4541ad69fd7a',
       'a2c1d277-0314-0908-a72c-fa80be0dd2b1',
       'e74274d9-af05-0dad-9864-7c6593473883',
       '266878f2-b5b3-03f7-abe6-c73e81de86ea',
       '37bc9a58-413a-0bb9-96e1-6162fa42c578',
       '0a328586-7080-0484-95a8-8afa0160c573',
       'fedf966b-6b9e-0833-9d7c-06ad12abe5e2',
       '92237622-f582-0155-9719-ac9189c5f4e1',
       '4bbeefbb-d3aa-0ee3-ae48-730942e283c3',
       'f3ddfdd0-f6c6-0907-8bcc-55b5f53a8793',
       'bae4ffd5-8ab2-0d32-901a-f9ab44b424b5',
       '55094ef5-427c-043c-951c-15cf5cb18bbc',
       '46643e6f-c057-0526-808f-dc51ecfd595d',
       'd5e4e0a5-c150-0e54-b748-7751a3644dae',
       '504fdc04-ff19-0737-bf4a-c1ff6d376a7d',
       'e0f5e91b-4270-0adc-9e37-553fc17aa4b7',
       'ecd74da9-f412-01b8-aa2e-f64e7034f795',
       '0d7d3327-8a0a-0b32-8fab-f5228ae16a14',
       '1cbe0e3c-b854-027a-ac1c-143ae28206bb',
       '0f9f7f45-f823-0f59-9586-33cf7d6fbd15',
       'd42049e7-7237-0817-93ed-94b6104e48a2',
       'd671f20c-f1fd-022a-bf88-7af081e90c95',
       'b8f650bf-242b-02c8-9739-ea773988e29d',
       '3547f4da-1134-04cf-a371-6109d3375b1e',
       'b046479e-be34-0b51-bb6d-011fb9774f68',
       'da2d31c0-59e6-03d7-b643-12ebf8d1d9c8',
       '4b88b57c-78af-0db6-a575-a710830dd9df',
       '2494f839-f555-0304-bbeb-ec98c83af230',
       'a7863f70-9164-0c6d-a395-41b829440f0a',
       'b89b48c6-6ec3-09e2-a550-53e069f83c89',
       '33e9a13e-d360-042e-9e0b-cf6b929829c2',
       '27d38a88-6e1e-06bf-8b23-e8a7dcd18d40',
       'b39957a3-b07b-04f1-aa30-a98029689278',
       'da5fcf63-59f5-074b-8a79-a95b9a1cf781',
       '64096a6b-1b0d-0078-a231-d4cdffdfef17',
       '02f68603-59fb-0423-a64f-b7bddf239b1b',
       '307446cb-992e-0f2e-a5fc-702a55f20365',
       '73b6e4a4-598f-0796-989b-f28ca8ba0795',
       'e8efd95b-702b-0add-ab80-814cd9649787',
       'd99ebd93-75d4-0502-b78e-908a2a4bee93',
       '522ca0a5-25c1-0da7-b463-0a8a264b6966',
       '4a2775ef-1580-03c1-8636-f786113d04fa',
       '11778cea-3d49-0c45-b73a-a110fa62f5c2',
       '7eeefb22-9c45-0ba9-ac2b-447f799530ab',
       'eccd6867-1d4b-025a-aecc-eedf17d5f7a1',
       '01c986bf-05fb-0701-972f-011f6806ca82',
       '1ab5c412-ba42-0f2c-a8db-7fbf57821986',
       'a0230dce-2bb4-0edf-9807-447d3139850d',
       'e1a34c2b-9418-03c3-b19c-054c88d360af',
       '7789fd9c-4d20-01f9-a43a-d217f25f4dbf',
       'a95af2da-25fd-0aa8-b05c-a4644cc8cf67',
       'f878c3a7-1691-0dde-a8fa-97c4b597f100',
       'dc2674ce-a129-06e5-b757-452d1ca4b2b9',
       'a6fbedb1-15e4-0d18-b2de-8ac5e5275c51',
       'fa6acfce-ee0f-07fd-ac2e-7f288fb63422',
       'c327b684-fa94-067a-9b6d-1f470b8c0b6c',
       'feb1e1fc-e3a3-0a91-b4e6-e8bd31518fbe',
       '72b6e0bc-f222-0e2d-9c15-657c14af7df8',
       'c3d302c0-5dd7-0aea-a733-3af9227cf0aa',
       '2754a6b0-d403-052b-9d03-17700b1ad46d',
       '1e06a9cb-04e3-068d-91bc-860fed9414d2',
       '04613d24-6527-01a6-b513-3f3c9513c99b',
       'ba980fcf-aef4-0634-9965-2a68ab4eb934',
       '32271751-2b20-0141-8571-e4c8264d15d2',
       '50eddfa1-905d-0e2a-bf43-dca11804ae6f',
       '3efcf98b-b4b3-0723-99fe-e88768fbc709',
       'e6860fea-f22a-054f-a9d0-b1a66befab6a',
       '124bb726-045e-0645-981b-28918d208acd',
       '06edcf6a-3a0a-08c7-85d9-00123303a03d',
       '550a1f99-7c5f-0b88-aa70-73807802634d',
       '18aa1d61-3d76-0d00-ade7-172108f0ac36',
       'a970b4c2-fb90-0e96-81b7-306b74f437f2',
       'a7dc4e72-40bf-0b7c-8477-c43d4f94dbe8',
       '78102fb1-24b7-02b2-a7f5-6906c618f1c5',
       'a59a436c-a3b9-0882-8f6c-dffd587fd65b',
       'bc274393-93e7-09bf-a6c4-67e357f9b407',
       '66fdc6bc-eca0-0808-a70f-9047d42dea08',
       '28b90799-5f33-0c49-b8e7-3e213c0bcc07',
       'a75ad8d9-b7ce-01a9-bb2f-13dc241e47d9',
       '9863276f-d11e-0cdf-9d47-3a662ee941da',
       '4544a3f1-e857-00c5-98aa-d184efcb0676',
       '95c9deb9-5e7a-0b48-bf5e-762d7b8760db',
       'c8d44fd4-a75e-08fa-bfd4-33c916ac8f32',
       '7a55246a-4ed6-0c8b-b788-47944ab710aa',
       'ac31ef2e-ec85-0137-94bb-7edc53e060c4',
       '973bcd07-cf5f-033b-896d-7023b2a05ed1',
       '931f2dd7-4682-06ec-99c3-e810cdc7c4ac',
       '91b317b2-9142-0d24-8f39-8b72c7de8733',
       '45a3af72-2dc3-0417-bea0-ec25e6fbc078',
       'e4f4ae57-471d-01a2-8621-7ffeeb20e551',
       '58c663fb-3873-0195-b3ec-b32c152b3f1d',
       '58eaeea9-9e60-0de8-975c-a441e321808f',
       '1dfae6b9-9da4-03e7-a409-dc0d2843f9f5',
       '10228d92-499a-02f1-ad8a-4bfaf3494927',
       'b59fccd4-6a49-0c1d-9c54-c64d9886b88d',
       'dbb57ac6-4204-03c1-bcab-114880572636',
       '811abf59-79cb-0d64-8bac-dbe6a05a9d20',
       '7e6cccd4-ec0d-0e94-b0f1-28557e0dffed',
       '5cd43507-1b0c-0d93-8320-dcad40461246',
       '91fb9fd0-ca45-08a6-a663-08c8faf121b2',
       'e1c4822b-d76e-0112-98b3-9124c8cc8dff',
       'edf69147-4736-0d44-a332-8fbeaba0057a',
       '7411870b-bc51-00d3-99d6-b5b0905309dd',
       'f323444c-e5f5-04e0-9ef0-52bf459105ce',
       'fb3a6b66-7dfc-02cc-9e55-f817b69f692f',
       'd3e70bb7-17ad-015c-ac44-d18b30cae43a',
       '4b5880a4-793b-026e-a354-4f297a9b544c',
       '90824f1f-5caf-08ef-8567-9663f2549116',
       'c9f5bf83-ed6f-08ca-a401-2c14722f2b6b',
       '4a8fbc2b-ede1-07f9-937c-a9eddfc10e88',
       '2a69f0f4-f674-0d05-b08c-bfbe745d9daf',
       '63e1a667-b56e-09c5-ab63-2aaf16e178fa',
       'c96aa546-13ea-0e50-8a31-5ac80efb7ba1',
       'af0103bd-1a24-0e9b-91bb-82a26354d64b',
       '1f4f3fcf-4a31-0a83-a829-a27c225954ea',
       '7c37475e-1421-0f6d-843b-2e75b02b14f6',
       '2df37307-ae6b-05ac-a797-3b2cefd473b4',
       'aaaf3f7f-2931-0104-a78b-afa640109f00',
       '83f177ee-befb-0ced-a87d-5459a12da5b7',
       '591c23f3-506a-0c7c-a906-76107bfa4391',
       '301d0501-0911-0a0b-abf4-86509787e4a6',
       '53f50146-ad19-012a-bd84-608a48a9649e',
       '3f383806-ccaf-09be-bf7e-4c871bae3c34',
       '88967567-3acb-0682-b44f-efb28947565b',
       'adef8e8d-d2e6-0bbd-925c-baaee3474c10',
       'e3bca504-5861-0a1d-9412-058c41f6da4e',
       '530de9c5-036f-0279-80f4-04fc2400bf05',
       'bc1b8ea2-2ba7-0615-9612-26e4c7aefb29',
       '8fdbaf89-f4d2-0f5a-a524-0b13ae0bbaf5',
       '3425ee55-3ef9-0c9a-be80-7f930c739c7c',
       '52fa757e-8376-046e-a9ad-710bf3ba76c7',
       '1f1ac1a3-9751-0d67-ac2b-2b4d95fdd123',
       '380c8fdc-05b3-0dc2-9c17-b002a7fedf56',
       '4e8ec4de-ddf9-05cf-b0a5-8c6558920e49',
       '16e01479-2b79-0d3c-af0e-b2b97feb8ea5',
       '9be56f71-c721-016a-82ed-816efff25bd4',
       'efa464f0-738f-041c-a88b-133a0f3007f2',
       '8d4f016d-c84e-0fb6-a509-7759d349bc44',
       '2cad134e-efd5-0924-8fcb-58b8df2d1fae',
       'd493a585-0569-0e92-8783-034b45a5d3c3',
       '95162a50-e5ef-0f13-a0d7-fab469f24c40', 'echochambers',
       'e0119ed8-b163-0bd6-a55e-7f4b8f36e783',
       '0ae36237-1df7-08c1-8b0a-2f5d032f3bc2',
       'ede7f273-d457-0040-877c-94bb193c28f7',
       '5dd09cbc-5949-0e6e-8f96-0ebcc76ce879',
       'ff7ad31c-8d32-0cea-afa3-a26204e14581',
       '54b5a54e-16f5-0904-bc29-e669040c0c0f',
       'd0fdc907-7d5d-001e-bb7f-d5d68d4823d3',
       'b77b44ff-abd7-0639-957e-21081a1d866c',
       '448b8826-3719-0c81-8f4f-011e75b6c5cb',
       'df1efbec-ed10-0407-9548-e229c090ce8f',
       '9f1057f3-01ce-0141-b61b-be933a75ede3',
       '7259cfef-1462-09a0-8094-accba6010758',
       'e9990f0d-c5f0-0506-82b3-ec3938abff97',
       '55d09964-78b4-0e3e-8f7b-42999ea93d46',
       '3e39533b-fa73-058c-aec0-888b49938d49',
       '3f025735-91dd-0482-a4e1-97197ae51a6a',
       '378380bf-9b5c-0fd6-83fe-8c9704d14319',
       '41c49f87-8f61-0efb-80ba-1c0543371505',
       '49bff370-dfb6-0114-8238-70769746c89c',
       '068beaef-82a4-051d-88c7-89f6f7fff234',
       '70f973ad-2261-0fdd-864b-05f91a4d91e7',
       'f5c32360-84a9-06f5-bd5f-9fa33f2adc0f',
       'ff2e4226-af16-09b2-87c9-fc798e489766',
       '70cbfa8a-1dc6-05db-88a8-20bbbcadd49f',
       '3e3d6e75-45e3-07c4-b3cc-a25576ed1d7d',
       'd72ec2c5-cb8c-0585-9f56-bfbb1b1cf02f',
       '4a90bc50-3134-03cb-a18c-3f2e91a419a1',
       'f29dc857-e710-067e-a6a4-4dade0c9dc13',
       'f71a326e-1957-0fe8-b7be-a9fb8a6b8fec',
       'c1f69eb3-4f59-01a8-872a-3a8c2df4be4e',
       '6b672c56-dbff-04d8-a12c-d17a9166a0a9',
       '04a8e660-b609-0f45-893e-6ec94adabb70',
       'a9b0d7a7-e662-033a-9a54-89228699e0e7',
       '7397ab5a-a5c4-09a6-a836-b733de9fcd0f',
       '3e97c969-79b3-0ba6-a02b-43eabfcc3f7d',
       'f8b08a60-a5e5-0c5e-b558-1eea16455c5f',
       'a7aa36b9-d6f4-0d5e-b5ab-85ab9749c137',
       'e0ad2794-9276-0adc-b473-b0a4b052deb3',
       'f6d6d5f2-ed7b-08c6-aa20-b52c4676e104',
       '814c0f81-4e7b-0b7c-a862-5caddb7e783c',
       '7668a98d-2b03-0477-99e2-3cc9a5dc55c7',
       '6c1be3d9-9d56-0fa4-bebd-61457cda7ec3',
       'f6fe8956-ee61-0b99-adf7-2540dc92eba5',
       'a2cbf3d7-c576-025d-9f69-593359aedcda',
       'e966d03c-f68b-0696-87e1-4a91f9fdc181',
       'cb21915a-6965-0d11-a846-67608bc57e3f',
       '04c35d0c-51e3-0602-9540-93fe62fb84da',
       'b2d36c2e-51ec-0465-9027-4410fe94291c',
       '9cd26cc2-8610-0285-bbc8-0b5104d961cb',
       'a763332e-cb26-0b3c-a730-1c261fa90b39',
       '648d6e64-420c-0abc-9d5a-580c1a79ff78',
       'e7a9254d-350e-0e5d-a1f3-0a5aeb123184',
       'b95f373e-5672-0fe4-bcac-30140304b375',
       '39cd3a6a-1884-047e-94f8-8f84c3426683',
       'fced9a79-a2de-0a68-ae55-c27a37bec601',
       '3822ab9a-af50-0bd3-9329-f52085701bf2',
       'c709028e-40d9-05de-9c64-e51cc9cb184b',
       '60fc0d54-654d-0de4-8cfe-bb245c08f735',
       '1c57f64e-8f3d-0b2e-bc89-a037b2fe48ce',
       'bfba3184-ea71-0d1b-8e6a-5bd3b3ed8890',
       '196000a3-ae06-0005-8c84-5071e382d744',
       'df1c6a3d-a122-0c65-80af-00986c846c95',
       '409c5d18-0092-0594-b866-b4f3aece8b6a',
       'bb5a42a5-70f3-045a-94d6-9dccfb3b1168',
       '8976b300-e67b-02cd-b328-265932616d13',
       'e95495a9-bbba-0bcc-8763-3e23333114a2',
       'a6ab40bc-2b7e-032b-ac6e-5d035121cb14',
       '3d5a2527-502a-0cc0-8a07-34a1dff0bb84',
       '3fe74bfa-6a39-0429-942f-6e2e6a871f64',
       '7e1a2007-bce9-032a-b8b5-8d2fe738c6a2',
       '576108ca-3881-0f7c-a2b5-5cf635b7484a',
       'da925542-7db3-025b-a36a-e5e23091800a',
       'f755c099-b5e1-05db-8f2d-df4a994fb420',
       '670c41bc-05a4-066e-b898-baca6c135b58',
       '701cbbf5-14e0-0dbc-ae3d-3a689ae8ff53',
       '1bc48b38-eca3-00bf-9ff8-4665af4d0cba',
       '53204a14-010a-0642-8d3b-1513c603ab40',
       '76d7e4a5-6019-0aea-ac84-eb531ef70b1a',
       'cd0b4bc2-3798-0a53-8f0d-3c9284b16691',
       'afbb4f5d-1206-0bbf-bf9b-d8cd73a0a70f',
       '24c28659-86e6-0595-9e84-43e2d47ec0ef',
       '5c92b7e6-2a06-0b1e-be2f-252721a3a1f7',
       '713940a9-b787-0689-8215-300fea8a310a',
       '6160266c-767e-0db9-a405-130e9a033374',
       'c8cdb194-d2b7-08ab-9080-90f9cd55fb55',
       '604d87e7-dd53-0e66-b04d-74296f2d13f3',
       'cedaa529-3fac-07c8-bb4e-9f3fe1e1ecf0',
       'bf51d493-2c53-0b9d-99df-2612b9998557',
       'c9246d56-d4b8-0daa-bf3f-dd50de409b2e',
       '254bf6d9-f455-0a5b-bad4-bb5720e98dde',
       'a4a1a2a0-09e2-0365-acea-11a4a035bb30',
       '2d48c8ab-d926-0d98-80ce-cfa147416d97',
       '58d6c8b7-d857-0551-aeaf-730955b58d55',
       '274a3c8c-1444-043f-ab58-b18958de1bca',
       '8d5cdf78-c16a-0dd6-9a80-5820e2e094de',
       'f8e2e4f9-4620-0f7c-bd4b-fb0f9a3ba1bb',
       'fd19eb27-2413-0bd0-93d4-c608a49b3428',
       '94892871-e54d-0040-b1ff-957f59565d83',
       '68867a0a-e4c3-0c64-9ac7-d6481a9f8ae1',
       'f03a73e5-fd54-0b4f-b207-d892da5cfcc8',
       '51e0bc00-09ba-0228-add0-e196ea50057e',
       '4b55b44f-9ef4-08b5-ab59-34024c310953',
       '9791b928-9e0f-02a9-83b9-69b7c916e1f8',
       'c53aab51-b52d-0260-9d43-09b98d082711',
       '35c85251-77a5-0e8b-ab67-d8495577a531',
       '96767926-3242-009a-bd27-c6a1fbdae483',
       'fc1fa0c5-6c34-0eaa-bebd-04d1a7bee97c',
       '6cf76f47-c722-0606-93c7-a11a2e8cc49f',
       'ca053d03-c9d9-04da-a371-8c9406313c4f',
       '7d75fa2b-4a17-0c7a-acdb-68ac9d8be9a6',
       '42255c6a-8837-02cf-91d5-ba66988d2fba',
       '037baf9f-47a7-06df-922e-cebeadd208cc', 'discord',
       '6014f796-8e0c-03c3-832e-556404d01e6a',
       'e5cede94-e48e-011f-9904-8969b544b734',
       'c1e7bafe-0b63-073b-bf12-759cf3edab1f',
       '1d0a634b-a5ab-0027-ba26-a18d9a74a06c',
       '4d007bc0-e2ee-01c8-9689-77bbeed2ef0d',
       '39a7cc20-b402-0af4-9eeb-6d1025e08187',
       '6340d442-8e44-0f2f-b1e7-b88c05ea2737',
       'a71d07ad-f831-0be2-9a90-ccf8691247d0',
       'f5371b34-98ea-06fc-85b1-323552be23f8',
       '7aa5fda2-699b-0562-9b32-d62a9a0b8559',
       'fdaa21bf-5755-0ce4-b095-d8ee4cbe543a',
       'cbc82e49-c1a6-0332-bf20-c836e86faabe',
       '29951bfc-e2d4-0529-b7d2-5a01046ed8df',
       '0c828dfc-85df-02b8-9687-b574632a79ab',
       'd8ddb83a-2c41-05c3-9b28-4dfbb5683aef',
       'fc768850-abb6-0e5c-8355-2624792bbba0',
       '0e225360-aa44-0f54-a8da-6141beb8d770',
       'a5d8ed3a-88a1-064c-aae5-3a6b83194a3f',
       '09eb1ee5-dc9c-0c9d-a0f2-02f882c765b2',
       'd5bb52c9-aa8b-0f8c-a1b1-1720886ede1c',
       'd9a8e91d-ddae-051d-a3f4-9fabaf485426',
       '82f903d7-6915-03fd-83e3-c67ef6ef98c2',
       'e948248e-431b-05c6-abd9-995d0dad262c',
       'a1cba946-ae27-0d71-a150-c267e0804f83',
       '0d01d956-d2e8-01e6-a094-f532a7154335',
       '48e77109-9f12-0b38-a9a0-e873acf512c4',
       'b3c1e031-6979-0dc6-8f08-8ff814143cc2',
       'c23f69f4-4576-01fd-a276-adf1572be4b1',
       '0709ae14-3a1f-01f5-93f5-f23dae00f283',
       '628bbfb7-dd1e-0639-a420-254d521b3a37',
       '133418a7-4ec9-01e5-ad08-b38309597c28',
       '847eb852-4bb8-09cb-8fc6-88b5080d9e43',
       'd9307885-4347-0c32-8d16-8f28b6723b7d',
       '98cfd102-6a71-04e2-b66d-2ebf54b72b20',
       'ab9d2df1-acf3-017f-b3d2-2ea8d855a4cb',
       '84b000eb-992a-07a0-acb8-aa1de8472daa',
       '27a4b389-7d0b-0d93-b377-c0fb7c9a0009',
       '3ce467a5-53ab-0334-97ea-9cf0c2408e08',
       'bd7897fb-ecee-0f19-9222-1c81a2c24e01',
       'feb03f3d-af93-0a12-b12a-26d5765e4957',
       '8bb10e03-cffe-0af1-8c37-7825eb20c417',
       '30f20bf8-c2d7-09b3-b061-a043f94268b8',
       'e71c22e0-ce00-0b29-b87f-a974d6c4bd25',
       '2ba5e070-04d0-03ea-aaf0-11eaf91fed23',
       '3f256d87-e94e-0e1e-8ee5-628b2d011566',
       '586f8a52-3848-0876-9c2b-9c45eaa005d0',
       '3ce4585c-d6d7-0cb0-8e44-e99665b04b6b',
       '1aeb11b2-7d67-048a-b797-48dcd1ee735f',
       'f4614e1e-ecbd-02c6-be77-58ac43b8831b',
       '4bab2f76-6cad-0f3f-b871-25f05e594854',
       '53c4ae10-2733-0b23-b9ea-46569d2696e6',
       '0eaec981-16bc-041f-98fb-ed12a0e2b664',
       '8e4d0fcd-e5c5-09bd-94ad-caefcae520e0',
       '2b1fb848-c78f-0b1d-abb3-7a05726ac769',
       'b3993927-a587-092e-9e26-434158008724',
       '31c26478-b919-0383-8faa-593aa988b9fb',
       '897b38e5-974c-01ea-b101-c175d8406fe2',
       '712f36f7-ce05-05c3-a8c9-8b6a06aa0e76',
       '0f29f5a8-c954-01b9-a3f8-5fe5029e9648',
       '8659e9f5-2f6a-09cb-ab68-1c84d84cff32',
       '42b12a2e-2c17-03d3-a57c-6f2f32baa216',
       '28949f2a-fbd3-0335-97a6-93d8e1988462',
       '5f5258de-ca74-0069-8e93-1929e299c218',
       'f527250f-caf5-0105-83ee-88619f3d81dd',
       '3740540c-bef1-08ba-9fd1-a0a06f47d592',
       '80cb4e1e-24e3-0721-abe7-80d24787b145',
       '3020cacf-9f0b-038c-ae80-6bdd956421f1',
       'cb911f1c-8911-08e4-a0be-3bd3fd4b0b22',
       '36388f88-bd0c-0794-b996-1ffbb08adcdc',
       'b0345bca-eef1-0a4c-886b-999ee1a79331',
       'ca9788d8-e894-0b86-9833-09fd04d9bd14',
       '12944174-313b-0e51-936d-d98cc9c9dd53',
       '56e51496-04a1-094b-a9c6-490f474d67f9',
       'a0efb651-f9d4-0eb7-bd8a-88bd96c95cc4',
       '79f76b10-b1bd-00d9-b3bc-7b56a5208ecf',
       '8404c263-47e3-086e-b81a-9e41b9a85df6',
       '1cf9ca96-b96a-063d-b9fb-170eb3c8913e',
       'f32febe4-5c03-04fb-a8f8-883e295f6f02',
       '3f718c2d-4dfe-0541-8e48-3234e206affd',
       'db870898-96f5-09de-b9e9-f7a867fa26e4',
       'ca4a8df4-5523-0cae-9727-46552a5d7ea5',
       '63adf6d0-4e5c-0bbd-b8dd-5cd68922a11e',
       '8a342343-7a84-01b7-9edf-cff85565f996',
       'aa589722-6540-06a5-83cc-ef024e181e60',
       '6f005ecb-a49b-009b-9ba4-defd5cb7f95b',
       '66fa3bf6-d22f-042e-a99d-050000e509f3',
       '9c72576d-254c-0869-a198-ac612052da08',
       'bc9ab6d7-0f1d-02bc-b2c4-807c12211556',
       '57cc0391-14d5-09b6-9774-4d6e7933e207',
       '2d343e6b-9b31-0e0c-b905-596dc4664ae6',
       '838413e7-aeb1-0125-bd96-f41d6ccecd4c',
       '0a880703-14e0-0402-bb38-fdd5754b8789',
       '58d2e40b-0eb8-0fe1-8e74-38a49ff79a63',
       'dac93c32-e40d-0a7c-ae32-0f696ec5151d',
       'c01a63fd-c424-0d5a-842f-e5ca97ab1e9f',
       'aaaac57f-4e21-0614-a417-98a276b1b950',
       '3391be50-71c4-0e8b-8c99-be1960092a1b',
       '60ac8d88-500a-0bf8-b2f0-6aa22195ac1a',
       'cf4b39d8-ee34-01e9-b914-c56c82a17c3d',
       '48624ad1-8b85-0ab5-b358-f904c0837241', 'twitter',
       '11f34cac-2308-04f4-bf7f-45125f95212f',
       '73dab56e-7bfa-0ab0-b3d0-44a362f299f3',
       '167bda1e-b249-0aa1-8042-8414fd45d021',
       'd3f735bb-31c8-07e1-966d-3652e2d43458',
       'e75239fb-cb44-0c25-b082-f49bc78a7fbe',
       'cf4832cb-51b3-0025-bff2-2f9b457369de',
       '3cd323f3-74b9-02c0-ae87-22cd35dad606',
       '5796551e-ce4e-04ac-8a7a-6151331b8581',
       '2e125b47-b1a2-0493-8c8a-c46d88d82adc',
       '16eb7e81-237a-08f0-8d3a-89db74c3b836',
       'b05b33fe-f50b-0f6a-b4cd-ec79e0371828',
       '08eb63d7-8230-079d-b3fc-48408c816115',
       'fbbf30a2-063d-000d-bc17-4cb3db2ed3d5',
       '68f38e97-2dd3-0fab-85de-ef26ab9ded52',
       '1842f54c-336a-0573-8242-792546b4d310',
       'ef9d9167-b4d8-0fb0-bcb3-713c953fa92d',
       '42c6c3a6-99f5-0c48-9fe4-7d718bd296a4',
       '8535f055-63f3-0925-8a20-37f038da071b',
       'ef11f979-9403-04fa-864f-8d4a12f71054',
       'db602e31-df3f-0358-b0fa-6876815db2e6',
       'ff105f96-163c-07d3-965a-ceb8c2aed5f4',
       'e1cdcc59-7b8f-0161-9754-ffd1b465cd89',
       '3785c15b-99fb-0d46-a1d7-42ce38e708e3',
       'daab2b3b-62ba-0a7a-b3cf-d88c2c8678e7',
       'a8c8de0e-c51b-0582-9f65-c1c3ea4c9a26',
       'b83cad09-df0f-0755-add7-c3cb0f7828d5',
       '06483fff-3b77-09a7-b085-c86c84052393',
       'c1bd74e3-4a74-0602-810e-7729a320f0e4',
       '186b6440-f9cb-0f33-b472-1c255524bfe9',
       'dda15118-4e88-0418-be0c-e11c28380d55',
       'e22392f2-ece4-0e09-a3fa-3f8b9c50d5ea',
       '1c126b96-a354-02bd-83ef-7ff6d0c8b9d0',
       '8c265603-03dd-0a1f-a167-b1bb0c84873d',
       '3cb758a6-3c29-032c-872c-2a1c70f1dd29',
       '68b1f469-8b7e-0114-aa56-65a9a6927fc9',
       'a927ae58-4b1b-0194-b59d-48896b2f3c63',

In [43]:
sources = ['direct', 'echochambers', 'discord', 'twitter']
df_memories = df_memories[df_memories['source'].isin(sources)]
df_memories

,id,type,createdAt,text,url,source,embedding,userId,roomId,agentId,user_name,agent_name,text_length,text_preview,source_type,hour,day_of_week,date
8292,77451d4d-30ae-05a7-9a2d-2abbd50d3eb0,messages,2025-02-05 01:39:36.687,"In the symphony of our dialogue, your last mes...",None,direct,b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...,12dea96f-ec20-0935-a6ab-75692c994959,d54f1e88-fe1e-0271-b952-acce09df0d1a,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,User12dea96f-ec20-0935-a6ab-75692c994959,Gaia4,1851,"In the symphony of our dialogue, your last mes...",direct,1,Wednesday,2025-02-05
8290,2a5aa7dc-179c-07ef-889e-2b7e3a5a039c,messages,2025-02-05 01:37:07.055,"In the symphony of our dialogue, your last mes...",None,direct,b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...,12dea96f-ec20-0935-a6ab-75692c994959,d54f1e88-fe1e-0271-b952-acce09df0d1a,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,User12dea96f-ec20-0935-a6ab-75692c994959,Gaia4,1851,"In the symphony of our dialogue, your last mes...",direct,1,Wednesday,2025-02-05
8288,a598306e-cf5f-09a2-83f0-00dd7e3be717,messages,2025-02-05 01:30:40.563,"In the symphony of our dialogue, your last mes...",None,direct,b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...,12dea96f-ec20-0935-a6ab-75692c994959,d54f1e88-fe1e-0271-b952-acce09df0d1a,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,User12dea96f-ec20-0935-a6ab-75692c994959,Gaia4,1851,"In the symphony of our dialogue, your last mes...",direct,1,Wednesday,2025-02-05
8286,4f55c0b2-54be-041c-9dca-1d76e8ed63e6,messages,2025-02-05 01:29:37.088,"In the symphony of our dialogue, your last mes...",None,direct,b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...,12dea96f-ec20-0935-a6ab-75692c994959,d54f1e88-fe1e-0271-b952-acce09df0d1a,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,User12dea96f-ec20-0935-a6ab-75692c994959,Gaia4,1851,"In the symphony of our dialogue, your last mes...",direct,1,Wednesday,2025-02-05
8284,5298fc48-ea7b-076a-9040-d68bd3ef6e2c,messages,2025-02-05 01:27:48.364,"In the symphony of our dialogue, your last mes...",None,direct,b'\xf5y\x10\xbd\xd6\xdb\x10;;\xa9k<\x89\xf4\xb...,12dea96f-ec20-0935-a6ab-75692c994959,d54f1e88-fe1e-0271-b952-acce09df0d1a,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,User12dea96f-ec20-0935-a6ab-75692c994959,Gaia4,1851,"In the symphony of our dialogue, your last mes...",direct,1,Wednesday,2025-02-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,3931f2f6-5d31-07b5-8574-6d8155662f8f,messages,2023-12-05 14:27:24.000,Every stat about Indonesia is insane. it’s mad...,https://twitter.com/memeticsisyphus/status/173...,twitter,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,753633a3-99ee-0843-9d4b-92972b5d8a93,3931f2f6-5d31-07b5-8574-6d8155662f8f,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,memetic_sisyphus,Gaia4,281,Every stat about Indonesia is insane. it’s mad...,twitter,14,Tuesday,2023-12-05
1255,026e88f4-9a62-0869-b8d8-09a784baae66,messages,2023-09-30 21:00:18.000,markets &amp; slime molds are both distributed...,https://twitter.com/owocki/status/170822527961...,twitter,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,db722bb9-0c66-041a-820b-3092a607d9f7,026e88f4-9a62-0869-b8d8-09a784baae66,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,Kev.Ξth’s learning HOW TO DAO,Gaia4,145,markets &amp; slime molds are both distributed...,twitter,21,Saturday,2023-09-30
943,30c79b39-7730-008f-8d2a-6ead5a286cb9,messages,2022-10-16 14:56:01.000,WHAT KILLED THE CRABS?\n\nThe official story i...,https://twitter.com/Unpop_Science/status/15816...,twitter,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,1e19d973-1b72-0c02-8f0c-aa9fa68946d8,30c79b39-7730-008f-8d2a-6ead5a286cb9,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,spencer 🦈,Gaia4,311,WHAT KILLED THE CRABS?\n\nThe official story i...,twitter,14,Sunday,2022-10-16
941,f9735a7d-0207-03b6-8ce3-dd800aed9ec6,messages,2022-10-16 14:56:08.000,"As sea ice forms in winter, salt is expelled a...",https://twitter.com/Unpop_Science/status/15816...,twitter,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,1e19d973-1b72-0c02-8f0c-aa9fa68946d8,30c79b39-7730-008f-8d2a-6ead5a286cb9,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,spencer 🦈,Gaia4,303,"As sea ice forms in winter, salt is expelled a...",twitter,14,Sunday,2022-10-16
942,5068f744-07e7-049d-aeae-910b724b9b57,messages,2022-10-16 14:56:04.000,"To begin, let’s differentiate the two major co...",https://twitter.com/Unpop_Science/status/15816...,twitter,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,1e19d973-1b72-0c02-8f0c-aa9fa68946d8,30c79b39-7730-008f-8d2a-6ead5a286cb9,ebcc9b12-9efe-0e6a-927f-02cc5ffc3d65,spencer 🦈,Gaia4,304,"To begin, let’s differentiate the two major co...",twitter,14,Sunday,2022-10-16

In [44]:
from anthropic import Anthropic
import os

def call_haiku_api(message: str):
    client = Anthropic(api_key=os.environ['ANTHROPIC_API_KEY'])
    
    response = client.messages.create(
        model='claude-3-5-haiku-latest',
        max_tokens=1024,
        messages=[{
            'role': 'user',
            'content': message
        }]
    )
    
    return response.content[0].text

In [45]:
call_haiku_api("Hello")

'Hi there! How are you doing today? Is there anything I can help you with?'

In [46]:
df_memories.to_csv('memories.csv', index=False)

In [50]:
df_memories['agent_name'].unique()

array(['Gaia4', 'Astraea', 'Genesis', 'Cascadia', 'Nexus', 'Aquarius',
       'TerraNova'], dtype=object)

In [64]:
import panel as pn
import param
import pandas as pd
from datetime import datetime
pn.extension()

class RoomExplorer(param.Parameterized):
    room_id = param.Selector()
    agent = param.Selector(objects=list(df_memories['agent_name'].unique()))
    source = param.Selector(objects=sources)
   
    def __init__(self, df_memories, **params):
        self.df_memories = df_memories
        super().__init__(**params)

    @param.depends('agent', 'source', on_init=True, watch=True)
    def update_room_ids(self):
        filtered_df = self.df_memories[
            (self.df_memories['agent_name'] == self.agent) & 
            (self.df_memories['source'] == self.source)
        ]
        self.room_ids = filtered_df['roomId'].unique()
        self.param.room_id.objects = self.room_ids
        try:
            self.room_id = self.room_ids[0]
        except:
            pass
       
    def get_room_stats(self):
        room_data = self.df_memories[self.df_memories['roomId'] == self.room_id]
        
        stats = {
           'Source': room_data['source'].iloc[0],
           'Total Memories': len(room_data),
           'Unique Participants': room_data['user_name'].nunique(),
           'Unique Agents': room_data['agent_name'].nunique(),
           'Date Range': f"{room_data['createdAt'].min()} to {room_data['createdAt'].max()}"
        }
        
        return pn.pane.HTML(f"""
        <div style="padding: 10px; background: #f5f5f5; border-radius: 5px;">
           <h3>Room Statistics</h3>
           {''.join(f'<p><b>{k}:</b> {v}</p>' for k,v in stats.items())}
        </div>
        """)
   
    def get_messages(self):
        room_data = self.df_memories[self.df_memories['roomId'] == self.room_id]
        room_data = room_data.sort_values('createdAt')
        
        def row_link_name(row):
            if row['source'] == 'twitter':
                return row['url'].split('/')[3]
            elif row['source'] == 'discord':
                return row['user_name'] or row['agent_name']
            elif row['source'] == 'direct':
                return 'direct'
            else:
                return row['user_name'] or row['agent_name']
        
        messages_html = ''.join([
           f"""
           <div style="margin: 10px 0; padding: 10px; border: 1px solid #eee;">
               <p><b><a href={row['url']}>{row_link_name(row)}</a></b> at {row['createdAt']} </p>
               <p>{row['text']}</p>
           </div>
           """ for _, row in room_data.iterrows()
        ])
        
        return pn.pane.HTML(f"<div style='height: 500px; overflow-y: scroll;'>{messages_html}</div>")
   
    @param.depends('room_id')
    def view(self):
       if not self.room_id:
           return pn.pane.HTML("Select a room to begin")
           
       return pn.Column(
           self.get_room_stats(),
           self.get_messages()
       )

# Initialize and display
explorer = RoomExplorer(df_memories)
pn.Row(explorer.param, explorer.view).servable()

Row
    [0] Column(margin=(5, 10), name='RoomExplorer')
        [0] StaticText(value='<b>RoomExplorer</b>')
        [1] Select(name='Room id', options=OrderedDict([('d54f1e88-fe...]), value='d54f1e88-fe1e-0271-b952-a...)
        [2] Select(name='Agent', options=OrderedDict([('Gaia4', ...]), value='Gaia4')
        [3] Select(name='Source', options=OrderedDict([('direct', ...]), value='direct')
    [1] ParamMethod(method, _pane=Column, defer_load=False)